# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CFRP/RCF Hackathon Starter Kit
email: jamie@performantsoftware.com
description: > # this means to ignore newlines until "baseurl:"
  A starter kit for developers partipating in 
  the hackathon at the CFRP conference on
  May 19-21, 2016 at Harvard and MIT in 
  Cambridge MA (and elsewhere/when)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jamiefolsom.com" # the base hostname & protocol for your site
twitter_username: jamiefolsom
github_username:  jamiefolsom

# Build settings
markdown: kramdown
